-- Add MYSHARE_COMMENT and MYSHARE_REPLY to NotificationType enum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MYSHARE_COMMENT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MYSHARE_REPLY';
